import java.io.File

/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.6/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "microservices-architecture-spring"

// applications
File("${rootProject.projectDir}/apps").listFiles().forEach {
    if (it.isDirectory) {
        include("apps:${it.name}")
    }
}

// libraries
File("${rootProject.projectDir}/libs").listFiles().forEach {
    if (it.isDirectory) {
        include("libs:${it.name}")
    }
}




